#! /usr/bin/bash
# vi:set nu ai ap aw smd showmatch tabstop=4 shiftwidth=4:

# get our authorization token and userid
# first we call auth-token, which returns json, that we pass to "jq" to extract sessionToken and userId
# then we strip out the "quotes", and put them on same line with paste
# then that is all passed as stdin (<<<) to the read command that populates
# shell variables "token" and "userid"
read token userid <<< $(./auth-token | jq '.sessionToken,.userId' | sed 's/"//g' | paste - - )

# call the WebServices to change user password
# need to pass in our authentication.
# format the output as "id=x username=y"
curl -s \
  -H "X-Booked-SessionToken:${token}" \
  -H "X-Booked-UserId:${userid}" \
  -H "Content-Type:application/json" \
  -d @${1} "http://booked.tsand.org/Web/Services/index.php/Users/" | jq
