#! /usr/bin/bash
# vi:set nu ai ap aw smd showmatch tabstop=4 shiftwidth=4:

# this program will use curl to perform a REST call
# into booked services to obtain a sessionToken
# the authentication username and password are put in ~/.booked.auth
# ~/.booked.auth:
#      "username":"admin",
#      "password":"somepassword"
# 
# this file MUST be user perms protected.
# 


curl -s -X POST \
  "http://booked.tsand.org/Web/Services/index.php/Authentication/Authenticate" \
  -H "Content-Type: application/json" \
  -d "{ $(<~/.booked.auth) }"
