#! /usr/bin/bash
# vi:set nu ai ap aw smd showmatch tabstop=4 shiftwidth=4:

OIFS=$IFS
IFS='
'
for x in $(<${1?Must declare input file})
do
	OOIFS=$IFS
	IFS='|'
	set $x
	#echo "PASSWORD: $1"
	#echo "FIRSTNAME: $2"
	#echo "LASTNAME: $3"
	#echo "EMAILADDRESS: $4"
	#echo "USERNAME: $5"
	#echo "UID: $6"
	# create the student request file
	sed "s/\(<PASSWORD>\)/$1/g" user-form.tmpl > ${6}-tmp1.req
	sed "s/\(<FIRSTNAME>\)/$2/g" ${6}-tmp1.req > ${6}.req
	sed "s/\(<LASTNAME>\)/$3/g" ${6}.req > ${6}-tmp1.req
	sed "s/\(<EMAILADDRESS>\)/$4/g" ${6}-tmp1.req > ${6}.req
	sed "s/\(<USERNAME>\)/$5/g" ${6}.req > ${6}-tmp1.req
	sed "s/\(<UID>\)/$6/g" ${6}-tmp1.req > ${6}.req
	rm ${6}-tmp1.req
	./add-user ${PWD}/${6}.req
	IFS=$OOIFS
done

