version: "3.7"

services:
  db:
    image: linuxserver/mariadb:10.6.13
    container_name: librebooking-db
    restart: always
    networks:
      - mynet
    volumes:
      - vol-db:/config
      - vol-db-bu:/backup
      - /tmp/backup/db:/backup1
    ports:
      - "3306:3306"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - MYSQL_DATABASE=librebooking
      - MYSQL_ROOT_PASSWORD=mysqlrootpsw
      - MYSQL_USER=lb_user
      - MYSQL_PASSWORD=mysqluserpsw
  app:
    build:
      network: host
      context: .
      dockerfile: Dockerfile
    container_name: librebooking
    restart: always
    depends_on:
      - db
    networks:
      - mynet
    ports:
      - "80:80"
    volumes:
      - vol-app:/config
      - vol-app-bu:/backup
      - /tmp/backup/app:/backup1
    extra_hosts:
      - "beast4.tsand.org:10.0.0.215"
    environment: 
      - LB_DB_NAME=librebooking
      - LB_DB_USER=lb_user
      - LB_DB_USER_PWD=mysqluserpsw
      - LB_DB_HOST=db
      - LB_INSTALL_PWD=installpsw
      - LB_ENV=dev
      - LB_LOG_FOLDER=/var/log/librebooking
      - LB_LOG_LEVEL=debug
      - LB_LOG_SQL=false
      - TZ=America/New_York
volumes:
  vol-db:
    name: librebooking_data
  vol-db-bu:
    name: librebooking_data_backup
  vol-app:
    name: librebooking_conf
  vol-app-bu:
    name: librebooking_conf_backup

networks:
  mynet:
