#! /usr/bin/bash
# vi:set nu ai ap aw smd showmatch tabstop=4 shiftwidth=4:

psw="changeme"
usrname=${1?Must declare username}

eval $(./list-users | egrep "userName=${usrname}")
#echo "id: $id"
#echo "userName: $userName"

# get our authorization token and userid
read token userid <<< $(./auth-token | jq '.sessionToken,.userId' | sed 's/"//g' | paste - - )

# call the WebServices to change user password
# need to pass in our authentication.
# format the output as "id=x username=y"
curl -sS \
  -H "X-Booked-SessionToken:${token}" \
  -H "X-Booked-UserId:${userid}" \
  -H "Content-Type:application/json" \
  -d "{ \"password\":\"${psw}\" }" \
  "http://booked.tsand.org/Web/Services/index.php/Users/${id}/Password" | jq
